name: euronyxi-laravel-app
type: laravel
docroot: public
php_version: "8.3"
webserver_type: nginx-fpm
xdebug_enabled: false
no_project_mount: false

database:
  type: mariadb
  version: "11.4"

nodejs_version: "20"
mailpit_version: "v0.6.1"
web_environment:
  - APP_URL=https://euronyxi-laravel-app.ddev.site

# Ports for Vite/Livereload
web_extra_exposed_ports:
  - name: vite
    container_port: 5173
    http_port: 5173
    https_port: 5174